greeting:
  message: "hello"
camel:
  context:
    name: cdc-camel-context
  component:
    kafka:
      brokers: localhost:9092
      group-id: test-kafka-camel-group
      auto-offset-reset: earliest
      auto-commit-enable: true
      auto-commit-interval-ms: 5000
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
    debezium-postgres:
      topicPrefix: application
      offsetStorage: org.apache.kafka.connect.storage.KafkaOffsetBackingStore
      offsetStorageTopic: topic.cdc.offset.store.application
      databaseHostname: localhost
      databaseDbname: Application
      databaseUser: ${DB_USERNAME}
      databasePassword: ${DB_PASSWORD}
      databasePort: 5432
      pluginName: pgoutput
      schemaIncludeList: public
      tableIncludeList: public.application
      offsetFlushIntervalMs: 10000
quarkus:
  datasource:
    devservices:
      enabled: false
